skip_tags: true
clone_depth: 1
# Specify clone_folder so we can hard-code the Unix path equivalent below.
clone_folder: c:\projects\xapian
environment:
  matrix:
  - platform: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
  - platform: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - platform: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - platform: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  - platform: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
build_script:
  - echo ____________________________________________
  - bash -c "cygcheck -s"
  - C:\cygwin\bin\g++ --version
  - C:\cygwin\bin\i686-pc-cygwin-g++ --version
  - C:\cygwin\bin\i686-w64-mingw32-g++ --version
  - C:\cygwin\bin\x86_64-w64-mingw32-g++ --version
  - echo ____________________________________________
  - bash -c "cygcheck -s"
  - C:\cygwin64\bin\g++ --version
  - C:\cygwin64\bin\i686-w64-mingw32-g++ --version
  - C:\cygwin64\bin\x86_64-pc-cygwin-g++ --version
  - C:\cygwin64\bin\x86_64-w64-mingw32-g++ --version
  - echo ____________________________________________
  - cd C:\mingw-w64
  - dir /S /B *g++*.exe
  - echo ____________________________________________
  - bash -c "uname -a"
  - C:\MinGW\bin\g++ --version
  - C:\MinGW\bin\mingw32-g++ --version
  - echo ____________________________________________
