skip_tags: true
# A full clone takes 30 seconds, depth 20 takes 5 seconds.
#
# Using "shallow_clone: true" downloads the commit as a ZIP file so you might
# think that would be quicker still, but actually it seems to take ~15 seconds,
# and then bootstrap fails due to there not being a ".git" directory.
clone_depth: 20
# Specify clone_folder so we can hard-code the Unix path equivalent below.
clone_folder: c:\projects\xapian
environment:
  global:
    AUTOMATED_TESTING: 1
  matrix:
  - TOOLCHAIN: mingw
    platform: x86
  - TOOLCHAIN: mingw64
    platform: x86
  - TOOLCHAIN: mingw64
    platform: x64
  - TOOLCHAIN: cygwin
    platform: x86
  - TOOLCHAIN: cygwin
    platform: x64
  - TOOLCHAIN: msvc
    platform: x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    VCVARS_BAT: "\"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat\" x86"
  - TOOLCHAIN: msvc
    platform: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    VCVARS_BAT: "\"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat\" x64"
  - TOOLCHAIN: msvc
    platform: x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    VCVARS_BAT: "\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvars32.bat\""
  - TOOLCHAIN: msvc
    platform: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    VCVARS_BAT: "\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat\""
install:
  - ps: >-
      $env:CONFIGOPTS="--disable-documentation"
  - ps: >-
      if ($env:TOOLCHAIN -eq "mingw") {
        $env:PATH="C:\Mingw\bin;C:\Mingw\MSYS\1.0\bin;$env:PATH"
      } elseif ($env:TOOLCHAIN -eq "mingw64") {
        if ($env:Platform -eq "x86") {
          $env:PATH="C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin;C:\msys64\usr\bin;$env:PATH"
          $env:CONFIGOPTS+=" --host=i686-pc-mingw32"
        } else {
          $env:PATH="C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;C:\msys64\usr\bin;$env:PATH"
          $env:CONFIGOPTS+=" --host=x86_64-w64-mingw32"
        }
      } elseif ($env:TOOLCHAIN -eq "cygwin") {
        $env:PATH="C:\cygwin64\bin;$env:PATH"
        if ($env:Platform -eq "x86") {
          $env:CONFIGOPTS+=""
        } else {
          $env:CONFIGOPTS+=" --host=x86_64-pc-cygwin"
        }
      } elseif ($env:TOOLCHAIN -eq "llvm") {
        $env:PATH="C:\Program Files\LLVM\bin;c:\msys64\usr\bin;$env:PATH"
      } else {
        $env:PATH="c:\msys64\usr\bin;$env:PATH"
      }
  - ps: >-
      if ($env:Platform -eq "x64") {
        $env:CONFIGOPTS+=" --disable-backend-remote"
      }
  - ps: >-
      if ($env:TOOLCHAIN -ne "cygwin") {
        $env:CONFIGOPTS+=" --disable-backend-honey"
      }
  - if "%TOOLCHAIN%"=="mingw" bash -c "echo 'c:/mingw /mingw' >> /etc/fstab"
  - if "%TOOLCHAIN%"=="mingw" bash -c 'mingw-get install libz-dev'
  - if "%TOOLCHAIN%"=="mingw64" bash -c 'pacman -Sy --noconfirm zlib-devel'
  - if "%TOOLCHAIN%"=="cygwin" C:\cygwin64\setup-x86_64.exe -qnNdO -R C:/cygwin64 -s http://cygwin.mirror.constant.com -l C:/cygwin64/var/cache/setup -P file-devel -P zlib-devel
  - bash -c 'time ./bootstrap xapian-core'
  - if "%TOOLCHAIN%"=="msvc" call %VCVARS_BAT%
  - if "%TOOLCHAIN%"=="msvc" bash -c 'wget https://zlib.net/zlib-1.2.11.tar.gz && tar -xf zlib-1.2.11.tar.gz && mv zlib-1.2.11 zlib'
  - if "%TOOLCHAIN%"=="msvc" cd zlib
  - if "%TOOLCHAIN%"=="msvc" nmake -nologo -f win32\Makefile.msc
  - if "%TOOLCHAIN%"=="msvc" cd ..
  # Fetch pre-built unicode-data.cc to avoid having to get working tclsh.
  - curl https://oligarchy.co.uk/xapian/patches/unicode-data.cc > xapian-core\unicode\unicode-data.cc
  - ps: >-
      if ($env:TOOLCHAIN -eq "msvc") {
        $env:CC="cl -nologo"
        $env:CXX="c:/projects/xapian/INST/share/automake-1.15/compile cl -nologo"
        $env:CXXFLAGS="-EHsc"
        $env:CPPFLAGS="-Ic:/projects/xapian/zlib"
        $env:AR="lib"
        $env:LDFLAGS="-Lc:/projects/xapian/zlib"
      }
build_script:
  - bash -c 'time ./configure $CONFIGOPTS'
  - bash -c 'time make -j2' < nul
test_script:
  - bash -c 'time make check VERBOSE=1' < nul
