skip_tags: true
# A full clone takes 30 seconds, depth 20 takes 5 seconds.
#
# Using "shallow_clone: true" downloads the commit as a ZIP file so you might
# think that would be quicker still, but actually it seems to take ~15 seconds,
# and then bootstrap fails due to there not being a ".git" directory.
clone_depth: 20
# Specify clone_folder so we can hard-code the Unix path equivalent below.
clone_folder: c:\projects\xapian
environment:
  matrix:
  - platform: x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
  - platform: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
  - platform: x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - platform: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - platform: x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - platform: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - platform: x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  - platform: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  - platform: x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
  - platform: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
build_script:
  - dir C:\mingw-w64
  - bash -c "find c:/mingw-w64 -iname 'g++*.exe' -ls"
  - bash -c "find /mingw-w64 -iname 'g++*.exe' -ls"
  - bash -c "find /c/mingw-w64 -iname 'g++*.exe' -ls"
  - dir C:\MinGW
