skip_tags: true
clone_depth: 20
clone_folder: c:\projects\xapian
environment:
  global:
    AUTOMATED_TESTING: 1
  matrix:
  - TOOLCHAIN: mingw64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    platform: x64
install:
  - ps: >-
      $env:CONFIGOPTS="--disable-documentation"
  - ps: >-
      $env:PATH="C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;C:\msys64\usr\bin;$env:PATH"
  - ps: >-
      $env:CONFIGOPTS+=" --host=x86_64-w64-mingw32"
  - bash -c 'pacman -Sy --noconfirm --needed base-devel doxygen mingw-w64-x86_64-toolchain zlib-devel'
  - bash -c 'time ./bootstrap --download-tools=ifneeded --fetch-url-command="curl -L" xapian-core'
build_script:
  - bash -c 'which gcc'
  - bash -c 'gcc --version'
  - bash -c 'time ./configure $CONFIGOPTS --disable-documentation --disable-backend-honey --with-go || cat xapian-core/config.log'
  - bash -c 'echo __WIN32__ _WIN32 WIN32 __WIN64__ _WIN64 WIN64|gcc -E'
test_script:
  - bash -c 'echo dummy'

