skip_tags: true
clone_depth: 1
# Specify clone_folder so we can hard-code the Unix path equivalent below.
clone_folder: c:\projects\xapian
environment:
  matrix:
  - platform: x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
  - platform: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
  - platform: x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - platform: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - platform: x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - platform: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - platform: x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  - platform: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  - platform: x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
  - platform: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
build_script:
  - echo ____________________________________________
  - cd C:\mingw
  - dir /S /B *g++*.exe|bash -c 'while read x ; do echo "${x%?}" ; "${x%?}" --version ; done'
  - echo ____________________________________________
  - cd C:\cygwin
  - dir /S /B *g++*.exe|bash -c 'while read x ; do echo "${x%?}" ; "${x%?}" --version ; done'
  - echo ____________________________________________
  - cd C:\cygwin64
  - dir /S /B *g++*.exe|bash -c 'while read x ; do echo "${x%?}" ; "${x%?}" --version ; done'
  - echo ____________________________________________
  - cd C:\mingw-w64
  - dir /S /B *g++*.exe|bash -c 'while read x ; do echo "${x%?}" ; "${x%?}" --version ; done'
  - echo ____________________________________________
