dist: xenial
language: cpp
notifications:
  irc: "chat.freenode.net#xapian-devel"
env:
  global:
    - HOMEBREW_PACKAGES='doxygen help2man graphviz pngcrush libiconv libmagic pcre libsvm lua mono python2 python icu4c valgrind'
matrix:
  include:
    - os: osx
      before_install:
        - brew update
        # "brew install" unhelpfully errors out if any package listed is
        # already installed and up-to-date, but travis change what's installed
        # by default from time to time so it's brittle to just filter out those
        # installed by default from the list we need.  Instead we ignore the
        # exit status from "brew install", then check later that
        # "brew list --versions" says all the packages requested are installed.
        - brew install $HOMEBREW_PACKAGES || true
        - brew list --versions $HOMEBREW_PACKAGES
        - pip2 install sphinx docutils
        - pip3 install sphinx
        - mkdir -p /tmp/xapian-libsvm-fixed-include
        - ln -sF "`ls -1d /usr/local/Cellar/libsvm/3.*/include|tail -n 1`" /tmp/xapian-libsvm-fixed-include/libsvm
      env: PYTHON2=/usr/local/bin/python2 CXXFLAGS=-Wno-error=reserved-user-defined-literal CPPFLAGS=-I/tmp/xapian-libsvm-fixed-include PKG_CONFIG_PATH=/usr/local/opt/icu4c/lib/pkgconfig confargs='--prefix=/Users/travis/XapianInstall --with-libiconv-prefix=/usr/local/opt/libiconv' installcore='make -C xapian-core install'


before_script:
  # Bootstrap everything (including letor, which isn't done
  # by default), then configure using our chosen compiler.
  - ./bootstrap xapian-core xapian-applications/omega swig xapian-bindings xapian-letor
  - ./configure $confargs CC="$USE_CC" CXX="$USE_CXX"
script:
  - make
  - $installcore
  - make check VERBOSE=1 AUTOMATED_TESTING=1
  # grep '^' passes through all input while giving a non-zero exit status if
  # that input is empty.
  - git status --porcelain|grep '^' && { echo "The generated files listed above are not in .gitignore" ; exit 1; }; true
