name: CI

# Use bash by default on all platforms.
defaults:
  run:
    shell: bash

on:
  push:
    paths-ignore:
      - '.appveyor.yml'
      - NEWS
      - 'xapian-maintainer-tools/**'
  pull_request:
    branches: master
    paths-ignore:
      - '.appveyor.yml'
      - NEWS
      - 'xapian-maintainer-tools/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  makedist:
    name: 'make dist'
    runs-on: 'ubuntu-latest'
    env:
      LIBEXTRACTOR_PREFIX: '/usr/lib/x86_64-linux-gnu/libextractor'
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Install CCache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: makedist
    - name: Install package dependencies
      run: |
        sudo apt-get update
        sudo apt-get install \
            doxygen \
            graphviz \
            help2man \
            python3-docutils \
            pngcrush \
            python3-sphinx \
            uuid-dev \
            libpcre2-dev \
            libmagic-dev \
            lua5.4 \
            liblua5.4-dev \
            mono-devel \
            python3-dev \
            tcl \
            tcl-dev \
            libicu-dev \
            pkg-config \
            libpoppler-glib-dev \
            libglib2.0-dev \
            libe-book-dev \
            libetonyek-dev \
            libgepub-0.6-dev \
            libgmime-3.0-dev \
            libarchive-dev \
            libabw-dev \
            libcdr-dev \
            libextractor-dev \
            libextractor-plugins-all \
            libmwaw-dev \
            libreofficekit-dev libreoffice-calc libreoffice-draw libreoffice-impress libreoffice-writer \
            libtesseract-dev \
            tesseract-ocr-eng
    - name: bootstrap source tree
      run: |
        echo verbose=off > ~/.wgetrc
        ./bootstrap xapian-core xapian-applications/omega swig xapian-bindings xapian-letor
    - name: configure
      run: ./configure
    - name: make
      run: make -j2
#    - name: Run tests
#      run: make -j2 check VERBOSE=1 AUTOMATED_TESTING=1
    - name: Create distribution tarball
      run: |
        make dist
    - uses: actions/upload-artifact@v3
      with:
        path: |
          xapian-core/xapian-core-*.tar.xz
          xapian-applications/omega/xapian-omega-*.tar.xz
          xapian-bindings/xapian-bindings-*.tar.xz
          xapian-letor/xapian-letor-*.tar.xz
        retention-days: 1
        if-no-files-found: error
    - name: Check generated files are in .gitignore
      # grep '^' passes through all input while giving a non-zero exit status
      # if that input is empty.
      run: git status --porcelain|grep '^' && { echo "The generated files listed above are not in .gitignore" ; exit 1; }; true

  cygwin:
    runs-on: 'windows-latest'
    needs: makedist
    # `-o incr` needed as GHA supplies shell fragments with DOS EOLs.
    shell: C:\tools\cygwin\bin\bash.EXE --noprofile --norc -e -o igncr -o pipefail {0}
    steps:
    - name: Install Cygwin
      uses: egor-tensin/setup-cygwin@v4
      with:
        packages: gcc-g++ make libpcre2-devel zlib-devel liblua-devel lua perl python3-devel ruby-devel tcl-devel libcrypt-devel
      # php-devel is PHP7 still (2023-07-14)
    - name: Fetch distribution
      uses: actions/download-artifact@v3
    - name: Unpack distribution
      run: |
        mv artifact/* .
        rmdir artifact
        pushd xapian-core
        tar --strip-components=1 -xf xapian-core-*.tar.xz
        popd
        pushd xapian-applications/omega
        tar --strip-components=1 -xf xapian-omega-*.tar.xz
        popd
        pushd xapian-bindings
        tar --strip-components=1 -xf xapian-bindings-*.tar.xz
        popd
        pushd xapian-letor
        tar --strip-components=1 -xf xapian-letor-*.tar.xz
        popd
    # FIXME: ccache?
    - name: configure
      run: |
        export PERL_LIBS=`perl -MConfig -e 'print "-L$Config{archlib}/CORE" -lperl'`
        pushd xapian-core
        ./configure
        export XAPIAN_CONFIG=$PWD/xapian-config
        popd
        pushd xapian-applications/omega
        ./configure
        popd
        pushd xapian-bindings
        ./configure
        popd
        pushd xapian-letor
        ./configure
        popd
    - name: make
      run: |
        make -j2 -C xapian-core
        make -j2 -C xapian-applications/omega
        make -j2 -C xapian-bindings
        make -j2 -C xapian-letor
    - name: Run tests
      run: |
        make -j2 -C xapian-core check VERBOSE=1 AUTOMATED_TESTING=1
        make -j2 -C xapian-applications/omega check VERBOSE=1 AUTOMATED_TESTING=1
        make -j2 -C xapian-bindings check VERBOSE=1 AUTOMATED_TESTING=1
        make -j2 -C xapian-letor check VERBOSE=1 AUTOMATED_TESTING=1

  windows:
    runs-on: 'windows-latest'
    needs: makedist
    steps:
    - name: Fetch distribution
      uses: actions/download-artifact@v3
    - name: Unpack distribution
      run: |
        mv artifact/* .
        rmdir artifact
        pushd xapian-core
        tar --strip-components=1 -xf xapian-core-*.tar.xz
        popd
        pushd xapian-applications/omega
        tar --strip-components=1 -xf xapian-omega-*.tar.xz
        popd
        pushd xapian-bindings
        tar --strip-components=1 -xf xapian-bindings-*.tar.xz
        popd
        pushd xapian-letor
        tar --strip-components=1 -xf xapian-letor-*.tar.xz
        popd
    - name: Set up Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64
    - name: Install package dependencies
      run: |
        choco install make
    - name: Build zlib
      run: |

    - name: configure
      run: |
        mkdir zlib
        pushd zlib
        curl --retry 5 --retry-connrefused -L https://github.com/xapian/xapian-dev-deps/releases/download/current/zlib-1.2.13.tar.gz|tar --strip-components=1 -zxf -
        # Don't build zlib with -MD as it seems this flag needs to be used
        # consistently across the build.
        sed -i 's/\(^CFLAGS  *= *-nologo \)-MD /\1/' win32/Makefile.msc
        # Don't build zlib with a fixed base address on x64 as that gives
        # linker warning LNK4281.  FIXME: only for x64
        sed -i 's/-base:0x[0-9A-Fa-f]* //' win32/Makefile.msc
        nmake -nologo -f 'win32\Makefile.msc'
        popd
        export AR=lib
        export CC='cl -nologo'
        export CXX="$PWD/xapian-core/compile cl -nologo"
        # Standard C++ stack unwinding; assume extern "C" functions never throw.
        export CPPFLAGS="-I$PWD/zlib"
        export CXXFLAGS=-EHsc
        export LDFLAGS="-L$PWD/zlib"
        pushd xapian-core
        ./configure
        export XAPIAN_CONFIG=$PWD/xapian-config
        popd
        pushd xapian-applications/omega
        ./configure
        popd
        pushd xapian-bindings
        ./configure
        popd
        pushd xapian-letor
        ./configure
        popd
    - name: make
      run: |
        make -j2 -C xapian-core
        make -j2 -C xapian-applications/omega
        make -j2 -C xapian-bindings
        make -j2 -C xapian-letor
    - name: Run tests
      run: |
        make -j2 -C xapian-core check VERBOSE=1 AUTOMATED_TESTING=1
        make -j2 -C xapian-applications/omega check VERBOSE=1 AUTOMATED_TESTING=1
        make -j2 -C xapian-bindings check VERBOSE=1 AUTOMATED_TESTING=1
        make -j2 -C xapian-letor check VERBOSE=1 AUTOMATED_TESTING=1
