name: CI

# Use bash by default on all platforms.
defaults:
  run:
    shell: bash

on:
  push:
    paths-ignore:
      - '.appveyor.yml'
      - NEWS
      - 'xapian-maintainer-tools/**'
  pull_request:
    branches: master
    paths-ignore:
      - '.appveyor.yml'
      - NEWS
      - 'xapian-maintainer-tools/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  msvc2022:
    runs-on: 'windows-2022'
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        release: true # Use the pre-installed MSYS2
        path-type: inherit
        install: base-devel
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        show-progress: false
    - name: Set up Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64
    - name: make
      run: |
        cd xapian-core/tests
        cl -nologo -std:c++20 -DHAVE_CONFIG_H -I. -I.. -I../common -I../include -I./harness -WX -EHsc -E api_weight.cc || true
        cl -nologo -std:c++20 -DHAVE_CONFIG_H -I. -I.. -I../common -I../include -I./harness -WX -EHsc -c api_weight.cc
