name: CI

# Use bash by default on all platforms.
defaults:
  run:
    shell: bash

on:
  push:
    paths-ignore:
      - '.appveyor.yml'
      - NEWS
      - 'xapian-maintainer-tools/**'
  pull_request:
    branches: master
    paths-ignore:
      - '.appveyor.yml'
      - NEWS
      - 'xapian-maintainer-tools/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  makedist:
    name: 'make dist'
    runs-on: 'ubuntu-latest'
    env:
      LIBEXTRACTOR_PREFIX: '/usr/lib/x86_64-linux-gnu/libextractor'
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        show-progress: false
    - name: Install CCache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{ github.job }}
    - name: Cache bootstrap tools
      uses: actions/cache@v4
      with:
        path: |
          BUILD
          INST
        key: ${{ github.job }}-${{ runner.os }}-${{ hashFiles( 'bootstrap', 'patches/**' ) }}
    - name: Install package dependencies
      run: |
        sudo apt-get update
        sudo apt-get install \
            doxygen \
            graphviz \
            help2man \
            python3-docutils \
            pngcrush \
            python3-sphinx \
            uuid-dev
    - name: bootstrap source tree
      run: |
        # If we restored cached bootstrap tools their timestamps will be older
        # than checked out files, but we stored them based on a hash of the
        # files in git that determine what gets built so we know they are in
        # fact up to date.  Just touch any stamp files that exist.
        touch --no-create INST/*.stamp
        export PATH=/usr/lib/ccache:$PATH
        echo verbose=off > ~/.wgetrc
        ./bootstrap xapian-core xapian-letor
    - name: configure
      run: ./configure CC='ccache gcc' CXX='ccache g++' CFLAGS=-O0 CXXFLAGS=-O0
    - name: make
      run: make -j2
    - name: Create distribution tarball
      run: |
        make dist
    - uses: actions/upload-artifact@v4
      with:
        path: |
          xapian-core/xapian-core-*.tar.xz
          xapian-letor/xapian-letor-*.tar.xz
        # Files are already compressed so don't try to compress again.
        compression-level: 0
        retention-days: 1
        if-no-files-found: error
    - name: Check generated files are in .gitignore
      # grep '^' passes through all input while giving a non-zero exit status
      # if that input is empty.
      run: git status --porcelain|grep '^' && { echo "The generated files listed above are not in .gitignore" ; exit 1; }; true

  msvc2019:
    runs-on: 'windows-2019'
    needs: makedist
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        release: true # Use the pre-installed MSYS2
        path-type: inherit
        install: base-devel
    - name: Install CCache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{ github.job }}
        variant: sccache
    - name: Fetch distribution
      uses: actions/download-artifact@v4
    - name: Unpack distribution
      run: |
        mv artifact/* .
        rmdir artifact
        pushd xapian-core
        tar --strip-components=1 -xf xapian-core-*.tar.xz
        popd
        # Need libmagic for omega
        # pushd xapian-applications/omega
        # tar --strip-components=1 -xf xapian-omega-*.tar.xz
        # popd
        # pushd xapian-bindings
        # tar --strip-components=1 -xf xapian-bindings-*.tar.xz
        # popd
        pushd xapian-letor
        tar --strip-components=1 -xf xapian-letor-*.tar.xz
        popd
    - name: Set up Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64
    - name: Build zlib
      shell: bash
      run: |
        # Setup sccache for cl.
        ln /c/Users/runneradmin/.cargo/bin/{sccache.exe,cl.exe}
        PATH=/c/Users/runneradmin/.cargo/bin:$PATH
        mkdir zlib
        pushd zlib
        curl --retry 5 --retry-connrefused -L https://github.com/xapian/xapian-dev-deps/releases/download/current/zlib-1.2.13.tar.gz|tar --strip-components=1 -zxf -
        # Don't build zlib with -MD as it seems this flag needs to be used
        # consistently across the build.  Don't use -Zi -Fd"zlib" as
        # ccache/sccache don't seem to be able to handle that.
        #
        # Don't build zlib with a fixed base address on x64 as that gives
        # linker warning LNK4281.
        sed -i 's/\(^CFLAGS  *= *-nologo \)-MD \(.* \)-Zi -Fd"zlib" /\1\2/;s/-base:0x[0-9A-Fa-f]* //' win32/Makefile.msc
        # Only build the shared library.
        nmake -nologo -f 'win32\Makefile.msc' zlib1.dll
        ls -lrt
        popd
    - name: configure
      run: |
        export AR=lib
        export CC="cl -nologo"
        export CXX="$PWD/xapian-core/compile cl -nologo"
        export CPPFLAGS="-I$PWD/zlib"
        # Standard C++ stack unwinding; assume extern "C" functions never throw.
        export CXXFLAGS=-EHsc
        export LDFLAGS="-L$PWD/zlib"
        PATH=/c/Users/runneradmin/.cargo/bin:$PATH
        pushd xapian-core
        ./configure --enable-werror
        export XAPIAN_CONFIG=$PWD/xapian-config
        popd
        # pushd xapian-applications/omega
        # ./configure --enable-werror
        # popd
        # pushd xapian-bindings
        # ./configure --enable-werror
        # popd
        pushd xapian-letor
        ./configure --enable-werror
        popd
        echo
        cat xapian-core/config.log
    - name: make
      run: |
        PATH=/c/Users/runneradmin/.cargo/bin:$PATH
        make -j2 -C xapian-core
        echo XYZZY
        ls -l xapian-core/.libs
        # make -j2 -C xapian-applications/omega
        # make -j2 -C xapian-binding
        make -j2 -C xapian-letor
    - name: Run tests
      run: |
        PATH=/c/Users/runneradmin/.cargo/bin:$PATH
        export AUTOMATED_TESTING=1
        export VERBOSE=1
        make -j2 -C xapian-core check
        # make -j2 -C xapian-applications/omega check
        # make -j2 -C xapian-bindings check
        make -j2 -C xapian-letor check

  msvc2022:
    runs-on: 'windows-2022'
    needs: makedist
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        release: true # Use the pre-installed MSYS2
        path-type: inherit
        install: base-devel
    - name: Install CCache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{ github.job }}
        variant: sccache
    - name: Fetch distribution
      uses: actions/download-artifact@v4
    - name: Unpack distribution
      run: |
        mv artifact/* .
        rmdir artifact
        pushd xapian-core
        tar --strip-components=1 -xf xapian-core-*.tar.xz
        popd
        # Need libmagic for omega
        # pushd xapian-applications/omega
        # tar --strip-components=1 -xf xapian-omega-*.tar.xz
        # popd
        # pushd xapian-bindings
        # tar --strip-components=1 -xf xapian-bindings-*.tar.xz
        # popd
        pushd xapian-letor
        tar --strip-components=1 -xf xapian-letor-*.tar.xz
        popd
    - name: Set up Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64
    - name: Build zlib
      shell: bash
      run: |
        # Setup sccache for cl.
        ln /c/Users/runneradmin/.cargo/bin/{sccache.exe,cl.exe}
        PATH=/c/Users/runneradmin/.cargo/bin:$PATH
        mkdir zlib
        pushd zlib
        curl --retry 5 --retry-connrefused -L https://github.com/xapian/xapian-dev-deps/releases/download/current/zlib-1.2.13.tar.gz|tar --strip-components=1 -zxf -
        # Don't build zlib with -MD as it seems this flag needs to be used
        # consistently across the build.  Don't use -Zi -Fd"zlib" as
        # ccache/sccache don't seem to be able to handle that.
        #
        # Don't build zlib with a fixed base address on x64 as that gives
        # linker warning LNK4281.
        sed -i 's/\(^CFLAGS  *= *-nologo \)-MD \(.* \)-Zi -Fd"zlib" /\1\2/;s/-base:0x[0-9A-Fa-f]* //' win32/Makefile.msc
        # Only build the static library.
        nmake -nologo -f 'win32\Makefile.msc' zlib.lib
        ls -lrt
        popd
    - name: configure
      run: |
        export AR=lib
        export CC="cl -nologo"
        export CXX="$PWD/xapian-core/compile cl -nologo"
        export CPPFLAGS="-I$PWD/zlib"
        # Standard C++ stack unwinding; assume extern "C" functions never throw.
        export CXXFLAGS=-EHsc
        export LDFLAGS="-L$PWD/zlib"
        PATH=/c/Users/runneradmin/.cargo/bin:$PATH
        pushd xapian-core
        ./configure --enable-werror
        export XAPIAN_CONFIG=$PWD/xapian-config
        popd
        # pushd xapian-applications/omega
        # ./configure --enable-werror
        # popd
        # pushd xapian-bindings
        # ./configure --enable-werror
        # popd
        pushd xapian-letor
        ./configure --enable-werror
        popd
        echo
        cat xapian-core/config.log
    - name: make
      run: |
        PATH=/c/Users/runneradmin/.cargo/bin:$PATH
        make -j2 -C xapian-core
        echo XYZZY
        ls -l xapian-core/.libs
        # make -j2 -C xapian-applications/omega
        # make -j2 -C xapian-binding
        make -j2 -C xapian-letor
    - name: Run tests
      run: |
        PATH=/c/Users/runneradmin/.cargo/bin:$PATH
        export AUTOMATED_TESTING=1
        export VERBOSE=1
        make -j2 -C xapian-core check
        # make -j2 -C xapian-applications/omega check
        # make -j2 -C xapian-bindings check
        make -j2 -C xapian-letor check

  msvc2019-x86:
    runs-on: 'windows-2019'
    needs: makedist
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        release: true # Use the pre-installed MSYS2
        path-type: inherit
        install: base-devel
    - name: Install CCache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{ github.job }}
        variant: sccache
    - name: Fetch distribution
      uses: actions/download-artifact@v4
    - name: Unpack distribution
      run: |
        mv artifact/* .
        rmdir artifact
        pushd xapian-core
        tar --strip-components=1 -xf xapian-core-*.tar.xz
        popd
        # Need libmagic for omega
        # pushd xapian-applications/omega
        # tar --strip-components=1 -xf xapian-omega-*.tar.xz
        # popd
        # pushd xapian-bindings
        # tar --strip-components=1 -xf xapian-bindings-*.tar.xz
        # popd
        pushd xapian-letor
        tar --strip-components=1 -xf xapian-letor-*.tar.xz
        popd
    - name: Set up Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x86
    - name: Build zlib
      shell: bash
      run: |
        # Setup sccache for cl.
        ln /c/Users/runneradmin/.cargo/bin/{sccache.exe,cl.exe}
        PATH=/c/Users/runneradmin/.cargo/bin:$PATH
        mkdir zlib
        pushd zlib
        curl --retry 5 --retry-connrefused -L https://github.com/xapian/xapian-dev-deps/releases/download/current/zlib-1.2.13.tar.gz|tar --strip-components=1 -zxf -
        # Don't build zlib with -MD as it seems this flag needs to be used
        # consistently across the build.  Don't use -Zi -Fd"zlib" as
        # ccache/sccache don't seem to be able to handle that.
        sed -i 's/\(^CFLAGS  *= *-nologo \)-MD \(.* \)-Zi -Fd"zlib" /\1\2/' win32/Makefile.msc
        # Only build the static library.
        nmake -nologo -f 'win32\Makefile.msc' zdll.lib
        ls -lrt
        popd
    - name: configure
      run: |
        export AR=lib
        export CC="cl -nologo"
        export CXX="$PWD/xapian-core/compile cl -nologo"
        export CPPFLAGS="-I$PWD/zlib"
        # Standard C++ stack unwinding; assume extern "C" functions never throw.
        export CXXFLAGS=-EHsc
        export LDFLAGS="-L$PWD/zlib"
        PATH=/c/Users/runneradmin/.cargo/bin:$PATH:$PWD/zlib
        pushd xapian-core
        ./configure --enable-werror
        export XAPIAN_CONFIG=$PWD/xapian-config
        popd
        # pushd xapian-applications/omega
        # ./configure --enable-werror
        # popd
        # pushd xapian-bindings
        # ./configure --enable-werror
        # popd
        pushd xapian-letor
        ./configure --enable-werror
        popd
    - name: make
      run: |
        PATH=/c/Users/runneradmin/.cargo/bin:$PATH
        make -j2 -C xapian-core
        echo XYZZY
        ls -l xapian-core/.libs
        # make -j2 -C xapian-applications/omega
        # make -j2 -C xapian-binding
        make -j2 -C xapian-letor
    - name: Run tests
      run: |
        PATH=/c/Users/runneradmin/.cargo/bin:$PATH
        export AUTOMATED_TESTING=1
        export VERBOSE=1
        make -j2 -C xapian-core check
        # make -j2 -C xapian-applications/omega check
        # make -j2 -C xapian-bindings check
        make -j2 -C xapian-letor check

  msvc2022-x86:
    runs-on: 'windows-2022'
    needs: makedist
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        release: true # Use the pre-installed MSYS2
        path-type: inherit
        install: base-devel
    - name: Install CCache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{ github.job }}
        variant: sccache
    - name: Fetch distribution
      uses: actions/download-artifact@v4
    - name: Unpack distribution
      run: |
        mv artifact/* .
        rmdir artifact
        pushd xapian-core
        tar --strip-components=1 -xf xapian-core-*.tar.xz
        popd
        # Need libmagic for omega
        # pushd xapian-applications/omega
        # tar --strip-components=1 -xf xapian-omega-*.tar.xz
        # popd
        # pushd xapian-bindings
        # tar --strip-components=1 -xf xapian-bindings-*.tar.xz
        # popd
        pushd xapian-letor
        tar --strip-components=1 -xf xapian-letor-*.tar.xz
        popd
    - name: Set up Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x86
    - name: Build zlib
      shell: bash
      run: |
        # Setup sccache for cl.
        ln /c/Users/runneradmin/.cargo/bin/{sccache.exe,cl.exe}
        PATH=/c/Users/runneradmin/.cargo/bin:$PATH
        mkdir zlib
        pushd zlib
        curl --retry 5 --retry-connrefused -L https://github.com/xapian/xapian-dev-deps/releases/download/current/zlib-1.2.13.tar.gz|tar --strip-components=1 -zxf -
        # Don't build zlib with -MD as it seems this flag needs to be used
        # consistently across the build.  Don't use -Zi -Fd"zlib" as
        # ccache/sccache don't seem to be able to handle that.
        sed -i 's/\(^CFLAGS  *= *-nologo \)-MD \(.* \)-Zi -Fd"zlib" /\1\2/' win32/Makefile.msc
        # Only build the static library.
        nmake -nologo -f 'win32\Makefile.msc' zlib.lib
        ls -lrt
        popd
    - name: configure
      run: |
        export AR=lib
        export CC="cl -nologo"
        export CXX="$PWD/xapian-core/compile cl -nologo"
        export CPPFLAGS="-I$PWD/zlib"
        # Standard C++ stack unwinding; assume extern "C" functions never throw.
        export CXXFLAGS=-EHsc
        export LDFLAGS="-L$PWD/zlib"
        PATH=/c/Users/runneradmin/.cargo/bin:$PATH
        pushd xapian-core
        ./configure --enable-werror
        export XAPIAN_CONFIG=$PWD/xapian-config
        popd
        # pushd xapian-applications/omega
        # ./configure --enable-werror
        # popd
        # pushd xapian-bindings
        # ./configure --enable-werror
        # popd
        pushd xapian-letor
        ./configure --enable-werror
        popd
    - name: make
      run: |
        PATH=/c/Users/runneradmin/.cargo/bin:$PATH
        make -j2 -C xapian-core
        echo XYZZY
        ls -l xapian-core/.libs
        # make -j2 -C xapian-applications/omega
        # make -j2 -C xapian-binding
        make -j2 -C xapian-letor
    - name: Run tests
      run: |
        PATH=/c/Users/runneradmin/.cargo/bin:$PATH
        export AUTOMATED_TESTING=1
        export VERBOSE=1
        make -j2 -C xapian-core check
        # make -j2 -C xapian-applications/omega check
        # make -j2 -C xapian-bindings check
        make -j2 -C xapian-letor check
