name: CI

# Use bash by default on all platforms.
defaults:
  run:
    shell: bash

on:
  push:
    paths-ignore:
      - '.appveyor.yml'
      - NEWS
      - 'xapian-maintainer-tools/**'
  pull_request:
    branches: master
    paths-ignore:
      - '.appveyor.yml'
      - NEWS
      - 'xapian-maintainer-tools/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  makedist:
    name: 'make dist'
    runs-on: 'ubuntu-24.04'
    env:
      LIBEXTRACTOR_PREFIX: '/usr/lib/x86_64-linux-gnu/libextractor'
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        show-progress: false
    - name: Install CCache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{ github.job }}
    - name: Cache bootstrap tools
      uses: actions/cache@v4
      with:
        path: |
          BUILD
          INST
        key: ${{ github.job }}-${{ runner.os }}-${{ hashFiles( 'bootstrap', 'patches/**' ) }}
    - name: Install package dependencies
      run: |
        sudo apt-get update
        sudo apt-get install \
            doxygen \
            graphviz \
            help2man \
            python3-docutils \
            pngcrush \
            python3-sphinx \
            uuid-dev \
            libpcre2-dev \
            libmagic-dev \
            lua5.4 \
            liblua5.4-dev \
            mono-devel \
            python3-dev \
            tcl \
            tcl-dev \
            libicu-dev \
            pkg-config \
            libpoppler-glib-dev \
            libglib2.0-dev \
            libe-book-dev \
            libetonyek-dev \
            libgepub-0.7-dev \
            libgmime-3.0-dev \
            libarchive-dev \
            libabw-dev \
            libcdr-dev \
            libextractor-dev \
            libextractor-plugins-all \
            libmwaw-dev \
            libreofficekit-dev libreoffice-calc libreoffice-draw libreoffice-impress libreoffice-writer \
            libtesseract-dev \
            tesseract-ocr-eng
    - name: bootstrap source tree
      run: |
        # If we restored cached bootstrap tools their timestamps will be older
        # than checked out files, but we stored them based on a hash of the
        # files in git that determine what gets built so we know they are in
        # fact up to date.  Just touch any stamp files that exist.
        touch --no-create INST/*.stamp
        export PATH=/usr/lib/ccache:$PATH
        echo verbose=off > ~/.wgetrc
        ./bootstrap xapian-core xapian-applications/omega swig xapian-bindings xapian-letor
    - name: configure
      run: ./configure CC='ccache gcc' CXX='ccache g++'
    - name: make
      run: make -j2
    - name: Create distribution tarball
      run: |
        make dist
    - uses: actions/upload-artifact@v4
      with:
        path: |
          xapian-core/xapian-core-*.tar.xz
          xapian-applications/omega/xapian-omega-*.tar.xz
          xapian-bindings/xapian-bindings-*.tar.xz
          xapian-letor/xapian-letor-*.tar.xz
        # Files are already compressed so don't try to compress again.
        compression-level: 0
        retention-days: 1
        if-no-files-found: error
    - name: Check generated files are in .gitignore
      # grep '^' passes through all input while giving a non-zero exit status
      # if that input is empty.
      run: git status --porcelain|grep '^' && { echo "The generated files listed above are not in .gitignore" ; exit 1; }; true
    - name: Save log files
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: logs-${{ github.job }}-${{ github.sha }}
        overwrite: true
        path: |
          **/*.log

  mingw64-x86-64-cross:
    runs-on: 'ubuntu-22.04'
    needs: makedist
    steps:
    - name: Install CCache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{ github.job }}
    - name: Fetch distribution
      uses: actions/download-artifact@v4
    - name: Unpack distribution
      run: |
        mv artifact/* .
        rmdir artifact
        pushd xapian-core
        tar --strip-components=1 -xf xapian-core-*.tar.xz
        export XAPIAN_CONFIG=$PWD/xapian-config
        popd
        pushd xapian-letor
        tar --strip-components=1 -xf xapian-letor-*.tar.xz
        popd
    - name: Install package dependencies
      run: |
        sudo apt-get update
        # Stop mono binfmt trying to run .exe files.
        sudo apt-get purge mono-runtime
        sudo apt-get install \
            g++-mingw-w64-x86-64-win32 \
            mingw-w64-x86-64-dev \
            binutils-mingw-w64-x86-64 \
            libz-mingw-w64-dev \
            mingw-w64-tools \
            wine-binfmt \
            wine \
            wine64
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install wine32
    - name: configure
      run: |
        export EATMYDATA=
        export PATH=/usr/lib/ccache:$PATH
        pushd xapian-core
        ./configure --enable-werror --host x86_64-w64-mingw32
        export XAPIAN_CONFIG=$PWD/xapian-config
        popd
        pushd xapian-letor
        ./configure --enable-werror --host x86_64-w64-mingw32
        popd
    - name: make
      run: |
        export PATH=/usr/lib/ccache:$PATH
        make -j2 -C xapian-core
        make -j2 -C xapian-letor
    - name: Run tests
      run: |
        export AUTOMATED_TESTING=1
        export VERBOSE=1
        export WINEPATH="$PWD/xapian-core/.libs;/usr/lib/gcc/x86_64-w64-mingw32/`x86_64-w64-mingw32-g++ --version 2>/dev/null|head -n1|sed 's/.*) //;s/ .*//'`"
        export XAPIAN_TESTSUITE_RUNNING_UNDER_WINE=1
        make -j2 -C xapian-core check
        export WINEPATH="$PWD/xapian-letor/.libs;$WINEPATH"
        make -j2 -C xapian-letor check
    - name: Save log files
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: logs-${{ github.job }}-${{ github.sha }}
        overwrite: true
        path: |
          **/*.log
